// Generated by rstantools.  Do not edit by hand.

/*
    menbayes is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    menbayes is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with menbayes.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_marg_dr_pp_glpknown4_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_marg_dr_pp_glpknown4");
    reader.add_event(89, 87, "end", "model_marg_dr_pp_glpknown4");
    return reader;
}
template <typename T0__, typename T1__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__>::type, Eigen::Dynamic, 1>
segfreq4(const T0__& alpha,
             const T1__& xi,
             const int& g, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 12;
        validate_non_negative_index("p", "3", 3);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> p(3);
        stan::math::initialize(p, DUMMY_VAR__);
        stan::math::fill(p, DUMMY_VAR__);
        current_statement_begin__ = 13;
        if (as_bool(logical_eq(g, 0))) {
            current_statement_begin__ = 14;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        1.0, 
                        "assigning variable p");
            current_statement_begin__ = 15;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                        0.0, 
                        "assigning variable p");
            current_statement_begin__ = 16;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list()), 
                        0.0, 
                        "assigning variable p");
        } else if (as_bool(logical_eq(g, 1))) {
            current_statement_begin__ = 18;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        (0.5 + (0.25 * alpha)), 
                        "assigning variable p");
            current_statement_begin__ = 19;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                        (0.5 - (0.5 * alpha)), 
                        "assigning variable p");
            current_statement_begin__ = 20;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list()), 
                        (alpha / 4.0), 
                        "assigning variable p");
        } else if (as_bool(logical_eq(g, 2))) {
            current_statement_begin__ = 22;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        ((0.5 * alpha) + ((0.25 * (1 - alpha)) * (1 - xi))), 
                        "assigning variable p");
            current_statement_begin__ = 23;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                        ((0.5 * (1 - alpha)) * (1 + xi)), 
                        "assigning variable p");
            current_statement_begin__ = 24;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list()), 
                        ((0.5 * alpha) + ((0.25 * (1 - alpha)) * (1 - xi))), 
                        "assigning variable p");
        } else if (as_bool(logical_eq(g, 3))) {
            current_statement_begin__ = 26;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        (alpha / 4.0), 
                        "assigning variable p");
            current_statement_begin__ = 27;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                        (0.5 - (0.5 * alpha)), 
                        "assigning variable p");
            current_statement_begin__ = 28;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list()), 
                        (0.5 + (0.25 * alpha)), 
                        "assigning variable p");
        } else if (as_bool(logical_eq(g, 4))) {
            current_statement_begin__ = 30;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        0.0, 
                        "assigning variable p");
            current_statement_begin__ = 31;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                        0.0, 
                        "assigning variable p");
            current_statement_begin__ = 32;
            stan::model::assign(p, 
                        stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list()), 
                        1.0, 
                        "assigning variable p");
        } else {
        }
        current_statement_begin__ = 36;
        return stan::math::promote_scalar<fun_return_scalar_t__>(p);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct segfreq4_functor__ {
    template <typename T0__, typename T1__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__>::type, Eigen::Dynamic, 1>
    operator()(const T0__& alpha,
             const T1__& xi,
             const int& g, std::ostream* pstream__) const {
        return segfreq4(alpha, xi, g, pstream__);
    }
};
template <typename T0__, typename T1__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__>::type, Eigen::Dynamic, 1>
convolve(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& p1,
             const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& p2,
             const int& K,
             const int& khalf, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 44;
        validate_non_negative_index("q", "(K + 1)", (K + 1));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> q((K + 1));
        stan::math::initialize(q, DUMMY_VAR__);
        stan::math::fill(q, DUMMY_VAR__);
        current_statement_begin__ = 45;
        for (int k = 1; k <= (K + 1); ++k) {
            {
            current_statement_begin__ = 46;
            int iup(0);
            (void) iup;  // dummy to suppress unused var warning
            stan::math::fill(iup, std::numeric_limits<int>::min());
            stan::math::assign(iup,std::min((k - 1), (khalf - 1)));
            current_statement_begin__ = 47;
            int ilo(0);
            (void) ilo;  // dummy to suppress unused var warning
            stan::math::fill(ilo, std::numeric_limits<int>::min());
            stan::math::assign(ilo,std::max(0, (k - khalf)));
            current_statement_begin__ = 48;
            stan::model::assign(q, 
                        stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                        0.0, 
                        "assigning variable q");
            current_statement_begin__ = 49;
            for (int i = ilo; i <= iup; ++i) {
                current_statement_begin__ = 50;
                stan::model::assign(q, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                            (stan::model::rvalue(q, stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), "q") + (get_base1(p1, (i + 1), "p1", 1) * get_base1(p2, (k - i), "p2", 1))), 
                            "assigning variable q");
            }
            }
        }
        current_statement_begin__ = 53;
        return stan::math::promote_scalar<fun_return_scalar_t__>(q);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct convolve_functor__ {
    template <typename T0__, typename T1__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__>::type, Eigen::Dynamic, 1>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& p1,
             const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& p2,
             const int& K,
             const int& khalf, std::ostream* pstream__) const {
        return convolve(p1, p2, K, khalf, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_marg_dr_pp_glpknown4
  : public stan::model::model_base_crtp<model_marg_dr_pp_glpknown4> {
private:
        int N;
        matrix_d gl;
        double drbound;
        double ppbound;
        int g1;
        int g2;
        double mixprop;
public:
    model_marg_dr_pp_glpknown4(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_marg_dr_pp_glpknown4(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_marg_dr_pp_glpknown4_namespace::model_marg_dr_pp_glpknown4";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 58;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            current_statement_begin__ = 59;
            validate_non_negative_index("gl", "N", N);
            validate_non_negative_index("gl", "5", 5);
            context__.validate_dims("data initialization", "gl", "matrix_d", context__.to_vec(N,5));
            gl = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(N, 5);
            vals_r__ = context__.vals_r("gl");
            pos__ = 0;
            size_t gl_j_2_max__ = 5;
            size_t gl_j_1_max__ = N;
            for (size_t j_2__ = 0; j_2__ < gl_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < gl_j_1_max__; ++j_1__) {
                    gl(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 60;
            context__.validate_dims("data initialization", "drbound", "double", context__.to_vec());
            drbound = double(0);
            vals_r__ = context__.vals_r("drbound");
            pos__ = 0;
            drbound = vals_r__[pos__++];
            check_greater_or_equal(function__, "drbound", drbound, 0.0);
            check_less_or_equal(function__, "drbound", drbound, 1.0);
            current_statement_begin__ = 61;
            context__.validate_dims("data initialization", "ppbound", "double", context__.to_vec());
            ppbound = double(0);
            vals_r__ = context__.vals_r("ppbound");
            pos__ = 0;
            ppbound = vals_r__[pos__++];
            check_greater_or_equal(function__, "ppbound", ppbound, 0.0);
            check_less_or_equal(function__, "ppbound", ppbound, 1.0);
            current_statement_begin__ = 62;
            context__.validate_dims("data initialization", "g1", "int", context__.to_vec());
            g1 = int(0);
            vals_i__ = context__.vals_i("g1");
            pos__ = 0;
            g1 = vals_i__[pos__++];
            check_greater_or_equal(function__, "g1", g1, 0);
            check_less_or_equal(function__, "g1", g1, 4);
            current_statement_begin__ = 63;
            context__.validate_dims("data initialization", "g2", "int", context__.to_vec());
            g2 = int(0);
            vals_i__ = context__.vals_i("g2");
            pos__ = 0;
            g2 = vals_i__[pos__++];
            check_greater_or_equal(function__, "g2", g2, 0);
            check_less_or_equal(function__, "g2", g2, 4);
            current_statement_begin__ = 64;
            context__.validate_dims("data initialization", "mixprop", "double", context__.to_vec());
            mixprop = double(0);
            vals_r__ = context__.vals_r("mixprop");
            pos__ = 0;
            mixprop = vals_r__[pos__++];
            check_greater_or_equal(function__, "mixprop", mixprop, 0.0);
            check_less_or_equal(function__, "mixprop", mixprop, 1.0);
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 68;
            num_params_r__ += 1;
            current_statement_begin__ = 69;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_marg_dr_pp_glpknown4() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 68;
        if (!(context__.contains_r("alpha")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable alpha missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("alpha");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "alpha", "double", context__.to_vec());
        double alpha(0);
        alpha = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(0, drbound, alpha);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable alpha: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 69;
        if (!(context__.contains_r("xi")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable xi missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("xi");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "xi", "double", context__.to_vec());
        double xi(0);
        xi = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(0, ppbound, xi);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable xi: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 68;
            local_scalar_t__ alpha;
            (void) alpha;  // dummy to suppress unused var warning
            if (jacobian__)
                alpha = in__.scalar_lub_constrain(0, drbound, lp__);
            else
                alpha = in__.scalar_lub_constrain(0, drbound);
            current_statement_begin__ = 69;
            local_scalar_t__ xi;
            (void) xi;  // dummy to suppress unused var warning
            if (jacobian__)
                xi = in__.scalar_lub_constrain(0, ppbound, lp__);
            else
                xi = in__.scalar_lub_constrain(0, ppbound);
            // model body
            {
            current_statement_begin__ = 73;
            validate_non_negative_index("p1", "3", 3);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> p1(3);
            stan::math::initialize(p1, DUMMY_VAR__);
            stan::math::fill(p1, DUMMY_VAR__);
            current_statement_begin__ = 74;
            validate_non_negative_index("p2", "3", 3);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> p2(3);
            stan::math::initialize(p2, DUMMY_VAR__);
            stan::math::fill(p2, DUMMY_VAR__);
            current_statement_begin__ = 75;
            validate_non_negative_index("q", "5", 5);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> q(5);
            stan::math::initialize(q, DUMMY_VAR__);
            stan::math::fill(q, DUMMY_VAR__);
            current_statement_begin__ = 76;
            validate_non_negative_index("u", "5", 5);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> u(5);
            stan::math::initialize(u, DUMMY_VAR__);
            stan::math::fill(u, DUMMY_VAR__);
            current_statement_begin__ = 77;
            stan::math::assign(p1, segfreq4(alpha, xi, g1, pstream__));
            current_statement_begin__ = 78;
            stan::math::assign(p2, segfreq4(alpha, xi, g2, pstream__));
            current_statement_begin__ = 79;
            stan::math::assign(q, convolve(p1, p2, 4, 3, pstream__));
            current_statement_begin__ = 80;
            stan::math::assign(u, transpose(stan::math::to_row_vector(stan::math::array_builder<double >().add(0.2).add(0.2).add(0.2).add(0.2).add(0.2).array())));
            current_statement_begin__ = 81;
            stan::math::assign(q, add(multiply((1.0 - mixprop), q), multiply(mixprop, u)));
            current_statement_begin__ = 82;
            lp_accum__.add(uniform_log(alpha, 0.0, drbound));
            current_statement_begin__ = 83;
            lp_accum__.add(beta_log(xi, 1.0, 2.0));
            current_statement_begin__ = 84;
            for (int ind = 1; ind <= N; ++ind) {
                current_statement_begin__ = 85;
                lp_accum__.add(log_sum_exp(add(to_vector(get_base1(gl, ind, "gl", 1)), stan::math::log(q))));
            }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("alpha");
        names__.push_back("xi");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_marg_dr_pp_glpknown4_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double alpha = in__.scalar_lub_constrain(0, drbound);
        vars__.push_back(alpha);
        double xi = in__.scalar_lub_constrain(0, ppbound);
        vars__.push_back(xi);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            if (!include_gqs__ && !include_tparams__) return;
            if (!include_gqs__) return;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_marg_dr_pp_glpknown4";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "xi";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "xi";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
}; // model
}  // namespace
typedef model_marg_dr_pp_glpknown4_namespace::model_marg_dr_pp_glpknown4 stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
